# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160619_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate',
            name='user',
        ),
    ]
