# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_calculate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcpost',
            name='operand1',
            field=models.TextField(default='x'),
        ),
        migrations.AddField(
            model_name='calcpost',
            name='operand2',
            field=models.TextField(default='y'),
        ),
        migrations.AddField(
            model_name='calcpost',
            name='symbol',
            field=models.TextField(default='+'),
        ),
    ]
